### PR TITLE
Make sure :localized fields are properly restored

### PR DESCRIPTION
**Pull request by tomasc**

### CODE REVIEW

**Comment by tomasc** [comment]
Hi @tilsammans, here another PR – this time making sure the [`:localized` fields](https://docs.mongodb.com/ruby-driver/master/tutorials/6.0.0/mongoid-documents/#localized-fields) are correctly restored.

Even though the tests pass locally, there seems to be some issue on Codeship (I can't see the details). I think it might be some dependency installation problem or so.

Can you please check, ev. merge, ev. release new version? Thank you!

**Comment by tomasc** [comment]
I realised we need to process all embedded documents as well. Since that was getting bit complicated, I extracted it into a separate service.

**Comment by tilsammans** [comment]
hi @tomasc the sign2pay codeship was removed; so i'll remove this integration as well.

i don't work for the sign2pay organisation anymore, and you're probably best to fork this repo completely. i will give you access to rubygems (if you don't have it already).

**Comment by tomasc** [comment]
Hi @tilsammans sounds good. I can then hook this up to travis ci instead and release new version.

**Comment by tilsammans** [comment]
@tomasc exactly - travisci would be great. feel free to add me as a collab; i can certainly keep contributing.

closing this now so we can move to a fork.

**Comment by tilsammans** [comment]
btw, you should have received an invite for rubygems.org.

**Comment by tomasc** [comment]
Seems i have access at rubygems now.
Btw wouldnt it be better to transfer this whole repo rather than working on a fork?

**Pull request closed without merging**
