### PR TITLE
test on Mongoid 6

### PR DESCRIPTION
**Pull request by tomasc**

### CODE REVIEW

**Comment by tomasc** [comment]
Hi @tilsammans, i have relaxed the Mongoid dependency so that the gem can be used with Mongoid 6 as well. 

The tests pass locally, but fail on Codeship. I guess it might be a matter of upgrading ruby version or so. I can't access the Codeship log so don't know what the issue really is. Can you please check?

Once we get this to pass on the CI, let's please release new version.

Thank you!

**Comment by tomasc** [comment]
Hi @tilsammans, can we please merge this? Thanks!

**Comment by tilsammans** [comment]
Oops, this one fell between the cracks. Checking codeship now.

**Comment by tilsammans** [comment]
Aargh, I don't have access to that Codeship any longer. We'll have to setup a new CI.

**Comment by tilsammans** [comment]
@tomasc merged and released a new version. I brought the ruby version back to 2.2.2. I'm not against changing it, but if we do that we should probably use Travis CI to test multiple rubies.

**Comment by tomasc** [comment]
@tilsammans thank you!

**Pull request merged**
